### PR TITLE
Access/Dialog: Center and keep above on wayland

### PR DESCRIPTION
**Pull request by leolost2605**
Fixes elementary/portals#115

Requires elementary/gala#2027 (Otherwise it will crash when closed)

### CODE REVIEW

**Comment by danirabbit** [comment]
Ah I forgot this uses request portal! That's great because that makes sense for all of those tbh.

I'll have to write packaging for the pantheon lib so marking this as 'blocked' :sweat_smile:

**Review by danirabbit — CHANGES_REQUESTED** [review]
Ah okay so looking at this more, these request dialogs usually have a parent. I'm guessing that in this case we don't get a parent because it's being called from Gala and not really from system settings. So we probably should make sure we only do center/on top if we don't have a parent window

**Comment by leolost2605** [comment]
Ah right I forgot about that, fixed it :)

**Comment by danirabbit** [comment]
@leolost2605 I wrote packaging for libpantheon-wayland and it seems to be working as expected except that it crashes when switching between LoDPI and HiDPI. Which I guess is a problem in Gala? Or maybe in the library?

**Comment by danirabbit** [comment]
Oh sorry I'm silly you totally mentioned that already. Checking out the branch now

**Review by danirabbit — APPROVED** [review]
This is great! Thank you :)

**Pull request merged**
