### PR TITLE
Install a portals.conf file for the pantheon session 

### PR DESCRIPTION
**Pull request by nater1983**
While the existing pantheon.portal file describes our
implementation. The portals.conf file lets us select
which portal implementation(s) to use in the Pantheon session.

Ref #https://github.com/flatpak/xdg-desktop-portal/pull/955/

Since xdg-desktop-portal 1.17.0, the recommendation is for each desktop environment implementation XDG_CURRENT_DESKTOP=foo to provide a /usr/share/xdg-desktop-portal/foo-portals.conf specifying its preferred portal implementations.

### CODE REVIEW

**Comment by nater1983** [comment]
Ref https://github.com/flatpak/xdg-desktop-portal/pull/955/

**Review by nater1983 — COMMENTED** [review]
This can be changed as needed

For Pantheon I think this would look something like (untested):

**Comment by lenemter** [comment]
Isn't this the same as https://github.com/elementary/default-settings/pull/293?

**Comment by nater1983** [comment]
I guess so I didnt know it was in settings

**Pull request closed without merging**
